#!/bin/bash

#SBATCH --job-name=attention_image_mnist
#SBATCH --ntasks=1
#SBATCH --time=5:00:00
#SBATCH --partition=gpu


module load eb
module load Python/3.6.3-foss-2017b
module load CUDA/10.0.130
module load cuDNN/7.3.1-CUDA-10.0.130
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:/hpc/eb/Debian/cuDNN/7.3.1-CUDA-10.0.130/lib64:$LD_LIBRARY_PATH

cd /home/samigpu/Codes/tensor2tensor

conda activate myt2t
HEAD_DIR=/home/samigpu/Codes/tensor2tensor/

DATA_DIR=$HEAD_DIR/data/mnist/
LOGS_DIR=$HEAD_DIR/logs
MODEL=transformer_encoder
HPARAM=transformer_tiny
PROBLEM=image_mnist

t2t-trainer   --data_dir=$DATA_DIR   \
--problem=$PROBLEM  \
--hparams='batch_size=32' \
--worker_gpu=4 \
--model=$MODEL \
--hparams_set=$HPARAM \
--output_dir=$LOGS_DIR/$PROBLEM/$MODEL'_'$HPARAM